apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
  namespace: grv-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
      azure.workload.identity/use: "true"
  template:
    metadata:
      labels:
        app: open-webui
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: openwebui-sa
      containers:
      - name: open-webui
        image: csleetl.azurecr.io/grv-webui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "750m"
            memory: "750Mi"
          limits:
            cpu: "1500m"
            memory: "1.5Gi"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database-url
        - name: DATABASE_POOL_SIZE
          value: "10"
        - name: DATABASE_POOL_MAX_OVERFLOW
          value: "20"
        - name: DATABASE_POOL_TIMEOUT
          value: "30"
        - name: DATABASE_POOL_RECYCLE
          value: "1800"
        tty: true
        volumeMounts:
        - name: webui-volume
          mountPath: /app/backend/data
      volumes:
      - name: webui-volume
        persistentVolumeClaim:
          claimName: open-webui-pvc          