apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  namespace: grv-webui
spec:
  type: LoadBalancer  # Changed to LoadBalancer for Azure
  selector:
    app: open-webui
  sessionAffinity: ClientIP
  ports:
    - protocol: TCP
      port: 80       # Changed to port 80 for simplicity
      targetPort: 8080